services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5189:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_HMR_CLIENT_PORT: 5189
    command: bun run dev

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    profiles:
      - test
    environment:
      CI: "true"
    command: bun run test:e2e
